version: "3.9"

services:
  fastapi:
    build: .
    container_name: fastapi-app
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
      - ./htmlcov:/app/htmlcov
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/tododb
    depends_on:
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tododb
    ports:
      - "7432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
